# Generated by Django 2.2.2 on 2019-06-24 15:26

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='JtArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operate_username', models.CharField(auto_created=True, default='admin', max_length=30, verbose_name='操作人名称')),
                ('operate_uid', models.IntegerField(auto_created=True, default=123456789, verbose_name='操作人ID')),
                ('create_username', models.CharField(auto_created=True, default='admin', max_length=30, verbose_name='创建人名称')),
                ('create_uid', models.IntegerField(auto_created=True, default=123456789, verbose_name='创建人ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('operate_time', models.DateTimeField(auto_now=True, verbose_name='操作时间')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('slug', models.SlugField(blank=True, help_text='根据title生成的，用于生成页面URL，必须唯一', max_length=255, null=True, unique=True, verbose_name='Slug')),
                ('brief', models.CharField(max_length=50, verbose_name='摘要')),
                ('content', models.TextField(blank=True, default=None, null=True, verbose_name='内容')),
                ('read_count', models.IntegerField(default=0, verbose_name='浏览数')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('oppose_count', models.IntegerField(default=0, verbose_name='反对数')),
                ('comment_count', models.IntegerField(default=0, verbose_name='评论数')),
                ('cover_image_url', models.ImageField(blank=True, max_length=255, null=True, upload_to='news/%Y/%m', verbose_name='图片')),
                ('type', models.CharField(choices=[('0', '文字'), ('1', '图片'), ('2', '视频')], default=0, max_length=10, verbose_name='类型')),
                ('is_recommend', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '文章列表',
                'verbose_name_plural': '文章列表',
                'db_table': 'jt_article',
                'ordering': ['sort', '-create_time'],
            },
        ),
        migrations.CreateModel(
            name='JtJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operate_username', models.CharField(auto_created=True, default='admin', max_length=30, verbose_name='操作人名称')),
                ('operate_uid', models.IntegerField(auto_created=True, default=123456789, verbose_name='操作人ID')),
                ('create_username', models.CharField(auto_created=True, default='admin', max_length=30, verbose_name='创建人名称')),
                ('create_uid', models.IntegerField(auto_created=True, default=123456789, verbose_name='创建人ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('operate_time', models.DateTimeField(auto_now=True, verbose_name='操作时间')),
                ('job_name', models.CharField(max_length=50, verbose_name='职位名称')),
                ('slug', models.SlugField(blank=True, help_text='根据job_name生成的，用于生成页面URL，必须唯一', max_length=255, null=True, unique=True, verbose_name='Slug')),
                ('work_year', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='工作经验')),
                ('education', models.CharField(choices=[('0', '请选择'), ('1', '博士导师'), ('2', '博士后'), ('3', '博士'), ('4', '硕士'), ('5', '研究生'), ('6', '本科'), ('7', '大专'), ('8', '高中'), ('9', '初中'), ('10', '小学'), ('11', '其他')], default=0, max_length=10, verbose_name='学历')),
                ('work_prop', models.CharField(choices=[('0', '全职'), ('1', '兼职'), ('2', '自由职业'), ('3', '其他')], default=0, max_length=5, verbose_name='工作性质')),
                ('content', models.TextField(blank=True, default=None, null=True, verbose_name='招聘要求')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '工作机会',
                'verbose_name_plural': '工作机会',
                'db_table': 'jt_job',
                'ordering': ['sort', '-create_time'],
            },
        ),
        migrations.CreateModel(
            name='JtSysConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operate_username', models.CharField(auto_created=True, default='admin', max_length=30, verbose_name='操作人名称')),
                ('operate_uid', models.IntegerField(auto_created=True, default=123456789, verbose_name='操作人ID')),
                ('create_username', models.CharField(auto_created=True, default='admin', max_length=30, verbose_name='创建人名称')),
                ('create_uid', models.IntegerField(auto_created=True, default=123456789, verbose_name='创建人ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('operate_time', models.DateTimeField(auto_now=True, verbose_name='操作时间')),
                ('site_name', models.CharField(max_length=50, verbose_name='站点名称')),
                ('site_desc', models.CharField(max_length=150, verbose_name='站点描述')),
                ('site_author', models.CharField(max_length=100, verbose_name='作者')),
                ('site_company', models.CharField(max_length=100, verbose_name='公司')),
                ('address', models.CharField(max_length=150, verbose_name='底部显示地址')),
                ('telephone', models.CharField(max_length=11, verbose_name='底部显示电话')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('icp', models.CharField(max_length=15, verbose_name='备案号')),
                ('remark', models.CharField(max_length=200, verbose_name='备注')),
            ],
            options={
                'verbose_name': '站点配置',
                'verbose_name_plural': '站点配置',
                'db_table': 'jt_sysconfig',
            },
        ),
        migrations.CreateModel(
            name='JtComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operate_username', models.CharField(auto_created=True, default='admin', max_length=30, verbose_name='操作人名称')),
                ('operate_uid', models.IntegerField(auto_created=True, default=123456789, verbose_name='操作人ID')),
                ('create_username', models.CharField(auto_created=True, default='admin', max_length=30, verbose_name='创建人名称')),
                ('create_uid', models.IntegerField(auto_created=True, default=123456789, verbose_name='创建人ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('operate_time', models.DateTimeField(auto_now=True, verbose_name='操作时间')),
                ('uid', models.IntegerField(default=0, verbose_name='评论人id')),
                ('username', models.CharField(max_length=50, verbose_name='评论人')),
                ('target_uid', models.IntegerField(default=0, verbose_name='被评论人Id')),
                ('target_username', models.CharField(max_length=50, verbose_name='被评论人')),
                ('message', models.CharField(max_length=255, verbose_name='评论内容')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_audit', models.BooleanField(default=True, verbose_name='是否审核')),
                ('object_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.JtArticle', verbose_name='被评论文章')),
            ],
            options={
                'verbose_name': '评论列表',
                'verbose_name_plural': '评论列表',
                'db_table': 'jt_comment',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='JtUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('avatar', models.ImageField(default='avatar/default.png', max_length=200, upload_to='avatar/%Y/%m', verbose_name='用户头像')),
                ('qq', models.CharField(blank=True, max_length=20, null=True, verbose_name='QQ')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='手机号')),
                ('nick_name', models.CharField(max_length=30, verbose_name='昵称')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'jt_userprofile',
                'ordering': ['-id'],
                'abstract': False,
                'swappable': 'AUTH_USER_MODEL',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
